image:
  name: docker/compose:1.22.0
  entrypoint: ["/bin/sh", "-c"]

variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"

services:
    - docker:dind

stages:
    - Build
    
Build:
    stage: Build
    before_script:
        - docker version
        - docker-compose version
    script:
        - docker-compose down
        - docker-compose build
        - docker-compose up
    only:
        - master