version: '3'

services:
  nginx:
    image: stream-app-ngx
    networks:
      - stream
      - public
    labels:
      - 'traefik.docker.network=public'
      - 'traefik.enable=true'
      - 'traefik.sec.frontend.rule=Host:example.com'
      - 'traefik.sec.frontend.entryPoints=https'
      - 'traefik.sec.port=80'
      - 'traefik.sec.protocol=http'

  origin:
    image: stream-app-origin
    networks:
      - stream
      - public
    ports:
      - 1935:1935
    environment:
      - HLS_URL=https://video.example.com/hls/%stream%.m3u8
      - HLS_FRAGMENT=2s
      - HLS_PLAYLIST_LENGTH=10s
      - HLS_REQ_PER_SEC=20
      - HLS_REQ_BURST=5
      - CORS_URL=*
      - SECURE_LINK_SECRET=secret
    labels:
      - 'traefik.docker.network=public'
      - 'traefik.enable=true'
      - 'traefik.sec.frontend.rule=Host:video.example.com'
      - 'traefik.sec.frontend.entryPoints=https'
      - 'traefik.sec.port=80'
      - 'traefik.sec.protocol=http'

  app:
    image: stream-app-php
    networks:
      - stream
    volumes:
      - streamdata:/usr/src/app/data
    environment:
      - ENV=PROD
      - APP_NAME=StreamDash
      - DEFAULT_STREAM=mystream
      - DEFAULT_STREAM_TOKEN=mystreamtoken
      - DEFAULT_PASSWORD=passwd
      - STREAM_FLASH_URL=rtmp://example.com/stream/%stream%
      - STREAM_HLS_URL=https://video.example.com/hls/%stream%.m3u8?expires=%expire%&token=%token%&user=%user%
      - SECURE_LINK_SECRET=secret
      - SECURE_LINK_TTL=7200
    labels:
      - 'traefik.enable=false'

volumes:
  streamdata:

networks:
  stream:
  public:
    external: true
