version: '3'

services:
  nginx:
    build:
      context: ./
      dockerfile: ./nginx/app/Dockerfile
    ports:
      - 8080:80
    volumes:
      - .:/usr/src/app
    links:
      - app

  origin:
    build: ./nginx/origin
    ports:
      - 1935:1935
      - 8181:80

  app:
    build:
      context: ./
      dockerfile: ./fpm/Dockerfile
    environment:
      - STREAM_FLASH_URL=rtmp://192.168.1.33/stream/%stream%
      - STREAM_HLS_URL=http://192.168.1.33:8181/hls/%stream%.m3u8?expires=%expire%&token=%token%&user=%user%
    volumes:
      - .:/usr/src/app
      - ./data:/usr/src/app/data
