version: '3'

services:
  nginx-app:
    build: ./nginx/app
    ports:
      - 8080:80
    volumes:
      - .:/usr/src/app
    links: 
      - app

  nginx-stream-origin:
    build: ./nginx/origin
    ports:
      - 1935:1935

  app:
    build:
      context: ./
      dockerfile: ./fpm/Dockerfile
    volumes:
      - .:/usr/src/app