version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - .:/usr/src/app

  app:
    build:
      context: ./
      dockerfile: ./fpm/Dockerfile
    volumes:
      - .:/usr/src/app
      - logs:/usr/src/app/logs
    environment:
      docker: "true"

volumes:
  logs:
    driver: 'local'