version: '3'

services:
  nginx:
    build: 
      context: ./
      dockerfile: ./nginx/app/Dockerfile
    ports:
      - 8080:80
    volumes:
      - .:/usr/src/app
    links: 
      - app

  origin:
    build: ./nginx/origin
    ports:
      - 1935:1935
      - 8181:80

  app:
    build:
      context: ./
      dockerfile: ./fpm/Dockerfile
    volumes:
      - .:/usr/src/app
      - ./data:/usr/src/app/data